- name: Task3
  hosts: node1.example.com node2.example.com
  tasks:
  - name: Grub file
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: ^(GRUB_CMDLINE_LINUX=(?!.* {{item}})\"[^\"]+)(\".*)
      line: '\1 {{item}}=0\2'
    loop:
      - "biosdevname"
      - "net.ifnames"
            
  - name: Change grub
    command: grub2-mkconfig
